module.exports = {
  pathPrefix: '',
  siteUrl: 'https://abdulqudus.com',
  siteTitle: 'Jide Abdul-Qudus',
  siteDescription: 'Portfolio of Jide Abdul-Qudus',
  author: 'Jide Abdul-Qudus',
  postsForArchivePage: 3,
  defaultLanguage: 'en',
  disqusScript: process.env.DISQUS_SCRIPT || 'https://rolwinreevan.disqus.com/embed.js',
  pages: {
    home: '/',
    blog: 'blog',
    contact: 'contact',
    resume: 'resume',
    tag: 'tags',
  },
  social: {
    github: 'https://github.com/jideabdqudus',
    facebook: 'https://www.facebook.com/qudusini',
    twitter: 'https://twitter.com/jideabdqudus',
    instagram: 'https://www.instagram.com/theqoder/',
    rss: '/rss.xml',
  },
  contactFormUrl: process.env.CONTACT_FORM_ENDPOINT || 'https://getform.io/f/09a3066f-c638-40db-ad59-05e4ed71e451',
  googleAnalyticTrackingId: process.env.GA_TRACKING_ID || '',
  tags: {
    nsure: {
      name: 'nsure',
      projectName: 'Nsure-HRM',
      description: 'Dashboard Management System, built for a Human Resource Management Company.',
      color: '#0b8c3f',
      website: 'https://google.com',
      github: 'https://google.com',
    },
    postify: {
      name: 'postify',
      projectName: 'Postify',
      description: 'Postify is a social web app, poised to look and operate like Twitter. Built using ReactJS and Redux.',
      color: '#ec1025',
      website: 'https://google.com',
      github: 'https://google.com',
    },
    pss: {
      name: 'pss',
      projectName: 'Paysmosmo',
      description: 'E-Commerce website, containing admin dashboard, user dashboard systems.',
      color: '#055663',
      website: 'https://google.com',
      github: 'https://google.com',
    },
    tracker: {
      name: 'tracker',
      projectName: 'COVID-19 Tracker',
      description: 'An App tracking Numbers of Death, Infected and Recovered COVID-19 patients in all 186 countries.',
      color: '#202388',
      website: 'https://google.com',
      github: 'https://google.com',
    },
    contactkeeper: {
      name: 'contactkeeper',
      projectName: 'Contact-Keeper',
      description: 'A general purpose programming language that is widely used for developing various applications.',
      color: '#c79505',
      website: 'https://google.com',
      github: 'https://google.com',
    },
    hireme: {
      name: 'hireme',
      projectName: 'Hire Me',
      description: 'Online Business Directory that helps create connections between service professionals and businesses.',
      color: '#4cef23',
      website: 'https://google.com',
      github: 'https://google.com',
    },
    itmanager: {
      name: 'itmanager',
      projectName: 'IT Manager',
      description: 'An App built for the IT Department of a company, allows Complaints status review by a Super Admin.',
      color: '#f9c646',
      website: 'https://google.com',
      github: 'https://google.com',
    },
    wishingwell: {
      name: 'wishingwell',
      projectName: 'Wishing Well',
      description: 'Ever thought of a digital wishing well? Built to bring wishes to life through virtual means.',
      color: '#d923ef',
      website: 'https://google.com',
      github: 'https://google.com',
    },
  },
};
